### ISSUE TITLE
Doesn't work with Angular 7

### ISSUE THREAD

**Issue by Blaaznar** [smnbbrv/ngx-mat-codemirror#1]
Module not found: Error: Can't resolve 'rxjs-compat/Subject'

Changing it to `import { Subject } from 'rxjs'; ` fixes the issue.

**Comment by smnbbrv** [comment]
should be fixed in upcoming version, need some time fixing the build...

**Comment by smnbbrv** [comment]
please try 1.0.5

**Comment by Blaaznar** [comment]
Thanks for updating it - I can't find the new version on https://www.npmjs.com/package/ngx-mat-codemirror though.

**Comment by smnbbrv** [comment]
Sorry for that, the project is quite old (in Angular terms and versions), a bit hard to make it live again :) v1.0.4 should be available now

**Comment by Blaaznar** [comment]
Thanks a bunch! 👍
